name: Publish

on:
 push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Logseq Publish
        uses: pengx17/logseq-publish@main
        with:
          version: 0.6.5
          dest: www
      - name: Deploy to vercel
        env:
          VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
          VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
        run: |
          npm i -g vercel
          vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --scope xutingzhou www
