name: Publish

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Logseq Publish
        uses: pengx17/logseq-publish@main
        with:
          dest: www
